server {
    listen 5173;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Any route that doesn't have a file extension (e.g. /devices)
    # is routed to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # error_page 404 /index.html;

    # Static file caching
    location ~* \.(?:css|js|jpg|svg|png|gif|ico|eot|woff|woff2|ttf)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
