"""add invoice metadata to purchase

Revision ID: 5679b57ed1a8
Revises: 334c245fd24b
Create Date: 2026-08-20 13:48:46.067105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5679b57ed1a8'
down_revision: Union[str, Sequence[str], None] = '334c245fd24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('invoice_source', sa.String(), nullable=False, server_default='MANUAL'))
    op.add_column('purchases', sa.Column('original_invoice_filename', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('invoice_file_hash', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('supplier_invoice_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchases_invoice_file_hash'), 'purchases', ['invoice_file_hash'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_invoice_file_hash'), table_name='purchases')
    op.drop_column('purchases', 'supplier_invoice_number')
    op.drop_column('purchases', 'invoice_file_hash')
    op.drop_column('purchases', 'original_invoice_filename')
    op.drop_column('purchases', 'invoice_source')
    # ### end Alembic commands ###
