"""multi_tenant_models

Revision ID: 5b9ad98d06f1
Revises: 08373f006738
Create Date: 2026-08-19 14:14:33.866446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ad98d06f1'
down_revision: Union[str, Sequence[str], None] = '08373f006738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_monthly_transactions', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('drug_license_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.add_column('batches', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'organizations', ['organization_id'], ['id'])
    op.add_column('customers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('customers_phone_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    op.add_column('medicines', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medicines', 'organizations', ['organization_id'], ['id'])
    op.add_column('purchase_items', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_items', 'organizations', ['organization_id'], ['id'])
    op.add_column('purchases', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'organizations', ['organization_id'], ['id'])
    op.add_column('reward_transactions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reward_transactions', 'organizations', ['organization_id'], ['id'])
    op.add_column('sale_items', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_items', 'organizations', ['organization_id'], ['id'])
    op.add_column('sale_return_items', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_return_items', 'organizations', ['organization_id'], ['id'])
    op.add_column('sale_returns', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_returns', 'organizations', ['organization_id'], ['id'])
    op.add_column('sales', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'])
    op.add_column('settings', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'settings', 'organizations', ['organization_id'], ['id'])
    op.add_column('suppliers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    
    # --- DATA MIGRATION ---
    # 1. Create a Default Plan
    op.execute("""
        INSERT INTO plans (name, description, price, billing_cycle, max_users, max_products, max_monthly_transactions, is_active)
        VALUES ('Basic', 'Default Plan', 0.0, 'monthly', 10, 10000, 10000, true)
        ON CONFLICT DO NOTHING;
    """)
    
    # 2. Create a Default Organization
    op.execute("""
        INSERT INTO organizations (name, owner_name, email, phone, status, plan_id, created_at, updated_at)
        SELECT 'Default Pharmacy', 'Admin', 'admin@example.com', '0000000000', 'ACTIVE', 
               (SELECT id FROM plans WHERE name = 'Basic' LIMIT 1), NOW(), NOW()
        WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Default Pharmacy');
    """)
    
    # 3. Update all tables with the default organization_id
    tables = [
        'users', 'batches', 'customers', 'medicines', 'purchase_items', 'purchases', 
        'reward_transactions', 'sale_items', 'sale_return_items', 'sale_returns', 
        'sales', 'settings', 'suppliers'
    ]
    
    for table in tables:
        op.execute(f"""
            UPDATE {table} 
            SET organization_id = (SELECT id FROM organizations WHERE name = 'Default Pharmacy' LIMIT 1)
            WHERE organization_id IS NULL;
        """)
        
    # 4. Make organization_id NOT NULL for all tenant tables (except users, as super_admin can be null)
    tenant_tables = [
        'batches', 'customers', 'medicines', 'purchase_items', 'purchases', 
        'reward_transactions', 'sale_items', 'sale_return_items', 'sale_returns', 
        'sales', 'settings', 'suppliers'
    ]
    
    for table in tenant_tables:
        op.alter_column(table, 'organization_id', existing_type=sa.Integer(), nullable=False)
    
    # Also set default role for existing users to 'owner'
    op.execute("UPDATE users SET role = 'owner' WHERE role = 'staff' AND email = 'admin@example.com';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'organization_id')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_column('settings', 'organization_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'organization_id')
    op.drop_constraint(None, 'sale_returns', type_='foreignkey')
    op.drop_column('sale_returns', 'organization_id')
    op.drop_constraint(None, 'sale_return_items', type_='foreignkey')
    op.drop_column('sale_return_items', 'organization_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'organization_id')
    op.drop_constraint(None, 'reward_transactions', type_='foreignkey')
    op.drop_column('reward_transactions', 'organization_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'organization_id')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_column('purchase_items', 'organization_id')
    op.drop_constraint(None, 'medicines', type_='foreignkey')
    op.drop_column('medicines', 'organization_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_unique_constraint(op.f('customers_phone_key'), 'customers', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'organization_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'organization_id')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
