"""add supplier_id to purchases

Revision ID: 9fed02fe7cab
Revises: 5b9ad98d06f1
Create Date: 2026-08-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fed02fe7cab'
down_revision: Union[str, Sequence[str], None] = '5b9ad98d06f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'supplier_id')
    # ### end Alembic commands ###
